### ISSUE TITLE
How to add priority to a job

### ISSUE THREAD

**Issue by ig-semenov** [gyselroth/mongodb-php-task-scheduler#17]
Hello everyone, 
Could you explain, please, if it's possible to add a job priority to your code. I see some options as  "at", "timeout" and etc.,  but i don't see priority. I would like to know how difficult it's to add the one. Can i do it this way:
1. Add 1 more option - Priority 
2. Change the Queue.php/main method to select according to priority, here: 
  $cursor_jobs = $this->jobs->getCursor([
            '$or' => [
                ['status' => JobInterface::STATUS_WAITING],
                ['status' => JobInterface::STATUS_POSTPONED],
            ],
        ]);
3. Do the same stuff as in item 2 for Worker/processAll method.

Thanks.

So, i think, i found out you use a capped collection and a tailable cursor, there is only natural sorting available for such things: Tailable cursors do not use indexes and return documents in natural order.
Could you confirm that there is no possibility to add priority different than FIFO?

**Comment by raffis** [comment]
Priorities are not possible right now but may be a feature of an upcoming major version.

Your woraround will not work that easily since yes u can not sort capped collections during tailing. This would require additional features in the queue core of v4.

**Comment by ig-semenov** [comment]
thanks

**Comment by ig-semenov** [comment]
When are you planning to issue version 4?

**Comment by raffis** [comment]
> When are you planning to issue version 4?
Development did not even start yet, so this may take a while. No date known so far. But maybe I can introduce priorities in a minor version depending how much of the core needs to get changed.

I have opened #19 for this feature, you may receive updates from that issue.
