### ISSUE TITLE
$scheduler->addJob creates a usual collection (not capped)

### ISSUE THREAD

**Issue by ig-semenov** [gyselroth/mongodb-php-task-scheduler#18]
public function addJob(string $class, $data, array $options = []): Process
	{
		$document = $this->prepareInsert($class, $data, $options);

		$result = $this->db->{$this->job_queue}->insertOne($document);
...
This code ^ doesn't work properly, i think.

**Comment by raffis** [comment]
The job collection gets converted into a capped one as soon as you start a queue node.

**Comment by ig-semenov** [comment]
thanks, could you also answer on my question about priority. Is it possible to add priority as an option? or, because there is a tailable cursor it's not possible at all.

**Comment by ig-semenov** [comment]
thanks
