### ISSUE TITLE
Slow "Process::wait()" when dealing with many jobs

### ISSUE THREAD

**Issue by juckerf** [gyselroth/mongodb-php-task-scheduler#20]
If a lot of (several hundreds in my case) of jobs are submitted in little time, `Process::wait()` is really slow (sometimes about 30s between the actual end of the job and the end of the wait in my case).

If I change the cursorType in `MessageQueue::getCursor` to `Find::Tailable` (instead of `Find::TailableAwait`) the problem does not occur (but the cpu usage increases).

**Comment by juckerf** [comment]
The option `maxAwaitTimeMS` of `MongoDB\Operation\Find` could probably be interesting to minimize the wait time of the TAILABLE_AWAIT cursor

**Comment by raffis** [comment]
@juckerf you should get better results using v3.1.0 and the new method Scheduler::waitFor($stack), see https://github.com/gyselroth/mongodb-php-task-scheduler/blob/master/README.md#asynchronous-programming
