### ISSUE TITLE
why do you have this " 'worker' => new ObjectId()" when a new job is added

### ISSUE THREAD

**Issue by ig-semenov** [gyselroth/mongodb-php-task-scheduler#22]
Could you explain, please what is the meaning to have this:
mongodb-php-task-scheduler/src/Scheduler.php/prepareInsert method
$document = [
			..
			'worker' => new ObjectId(),
			...
		];
I added a job and the job has this in the DB:
{ "_id" : ObjectId("5c7d99dd3b775021615e86e3"), "class" : "Mail\\MailJob", "status" : 0, "created" : ISODate("2019-03-04T21:34:17.684Z"), "started" : ISODate("2019-03-04T21:34:17.684Z"), "ended" : ISODate("2019-03-04T21:34:17.684Z"), "worker" : ObjectId("5c7d99d93b775021615e86e2"), "data" : "Date: Mon, 04 Mar 2019 21:34:17 +0000\r\nSubject: Hello...\r\nFrom: root <root@localhost>\r\n\r\nWorld", "options" : { "at" : 0, "interval" : 0, "retry" : 0, "retry_interval" : 300, "force_spawn" : false, "timeout" : 0, "priority" : 60, "ignore_data" : false } }
There are no running workers yet.  What is ObjectId("5c7d99d93b775021615e86e2")???

**Comment by raffis** [comment]
> Could you explain, please what is the meaning to have this:
> mongodb-php-task-scheduler/src/Scheduler.php/prepareInsert method
> $document = [
> ..
> 'worker' => new ObjectId(),

From the simple fact that one can not change the size of records within a capped collection. See https://docs.mongodb.com/manual/core/capped-collections/#document-size

Therefore the initial job gets initialized with a random objectId for a worker.
As soon as the job gets executed by a worker, the worker will change the worker id in the job.
